/*
 * This source file was generated by the Gradle 'init' task
 */
package nr.dungeoncrawler;

import java.util.ArrayList;
import java.util.Scanner;

import org.checkerframework.checker.units.qual.s;

import nr.dungeoncrawler.entities.Monster;
import nr.dungeoncrawler.entities.Player;
import nr.dungeoncrawler.entities.Potion;
import nr.dungeoncrawler.enums.ConsumableNames;
import nr.dungeoncrawler.interfaces.Consumable;
import nr.dungeoncrawler.interfaces.Item;
import nr.dungeoncrawler.interfaces.Node;
import nr.dungeoncrawler.services.BattleService;
import nr.dungeoncrawler.services.DungeonService;
import nr.dungeoncrawler.services.ValidationService;

public class App {

    public static void main(String[] args) {
        oneLineOfSpace();
        Player player = new Player("player1");
        System.out.printf("Welcome %s!\n", player.getName());
        oneLineOfSpace();
        System.out.println("You are in a dungeon! Here is the map:");

        DungeonService dungeonService = new DungeonService();
        Node[][] level = dungeonService.generateLevel(5, 7);
        dungeonService.setLevel(level);
        int currentPlayerLevel = dungeonService.getCurrentPlayerLevel();
        dungeonService.printLevel(level);
        twoLinesOfSpace();

        System.out.println("You can only choose the rooms from the level you are currently in.");
        System.out.println("You move a level up when clearing a room.");
        System.out.println("Code to enter a room is the number of level + the number of room.");
        System.out.println("For example, to enter the first room in the first level, you enter 01.");
        oneLineOfSpace();
        System.out.println("YOU ARE CURRENTLY AT LEVEL " + dungeonService.getCurrentPlayerLevel());
        oneLineOfSpace();

        System.out.println("So which room do you want to enter?");

        Scanner scanner = new Scanner(System.in);
        ValidationService validationService = new ValidationService(scanner);
        String input = scanner.nextLine();
        input = validationService.validateChooseLevelInput(input, dungeonService);
        System.out.printf("You chose room %s",
                level[currentPlayerLevel][Integer.parseInt(input.substring(1)) - 1].getType());
        oneLineOfSpace();
        oneLineOfSpace();
        BattleService battleService = new BattleService();
        Monster monster = new Monster("gragas", 10, 3, 10);
        monster.addDrop(new Potion(ConsumableNames.HEALTH_POTION));
        battleService.setEnemy(monster);
        battleService.setPlayer(player);

        battleService.startBattle(); // simple implementation

        input = scanner.nextLine();
        input = validationService.validateChoiceInBattleInput(input, dungeonService);

        if (input.equals("1")) {
            player.attack(monster);
            System.out.println("Monster health after attack:" + monster.getHealth());
            oneLineOfSpace();
            if (monster.getHealth() <= 0) {
                battleService.endBattle();
            }
        }
        while (currentPlayerLevel != dungeonService.getLevel().length - 1) {
            System.out.println("You can go the next level.");
            currentPlayerLevel++;
            dungeonService.setCurrentPlayerLevel(currentPlayerLevel);
            System.out.println("YOU ARE CURRENTLY AT LEVEL " + dungeonService.getCurrentPlayerLevel());
            twoLinesOfSpace();
            System.out.println("Which room do you choose now?");

            input = scanner.nextLine();
            input = validationService.validateChooseLevelInput(input, dungeonService);
            System.out.printf("You chose room %s",
                    level[currentPlayerLevel][Integer.parseInt(input.substring(1)) - 1].getType());
            oneLineOfSpace();
        }
        System.out.println("You have cleared the dungeon!");
        System.out.println("You win!");
    }

    public static void twoLinesOfSpace() {
        System.out.print("\n\n");
    }

    public static void oneLineOfSpace() {
        System.out.println();
    }
}
